/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    commands: [ { type: 'autogenerated', dirName: 'commands' } ],
    dataDriven: [ { type: "autogenerated", dirName: 'data_driven' } ],
    sapi: [ { type: 'autogenerated', dirName: 'sapi' } ],

};

export default sidebars;
