/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    commands: [ { type: 'autogenerated', dirName: 'commands' } ],
    addonsSimple: [ { type: "autogenerated", dirName: 'addons_simple' } ],
    addonsComplex: [ { type: "autogenerated", dirName: 'addons_complex' } ],
    chinaVersion: [ { type: "autogenerated", dirName: 'china_version' } ],
    sapi: [ { type: 'autogenerated', dirName: 'sapi' } ],
    modapi: [ { type: "autogenerated", dirName: 'modapi' } ],
    devTemplate: [ { type: "autogenerated", dirName: 'dev_template' } ],

};

export default sidebars;
